### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ghost** [haveyouwantto/ParticleMusicGenerator#2]
I used the test5 class
But there is no effect going up in the error block
help
and i can't listen music

Or is this normal
Please tell me how to do it in Minecraft

i want [https://www.youtube.com/watch?v=ALoBPluGIZw](https://www.youtube.com/watch?v=ALoBPluGIZw) this effect

help please

![2020-06-16_16 16 27](https://user-images.githubusercontent.com/49273221/84743558-186b0c00-afed-11ea-968b-80f23d6ec623.png)

![2020-06-16_1
![2020-06-16_16 17 03](https://user-images.githubusercontent.com/49273221/84743577-1e60ed00-afed-11ea-8811-c3622343b96f.png)
![2020-06-16_16 17 09](https://user-images.githubusercontent.com/49273221/84743582-1f921a00-afed-11ea-9b87-e86053a9a5eb.png)

![2020-06-16_16 17 15](https://user-images.githubusercontent.com/49273221/84743551-16a14880-afed-11ea-8bc8-fa7147fb05fa.png)
![2020-06-16_16 16 58](https://user-images.githubusercontent.com/49273221/84743567-1bfe9300-afed-11ea-94af-de2367822f4b.png)

**Comment by haveyouwantto** [comment]
Well actually you need a mod called Another Color Block, and you'll also need a resource pack called soma's resource pack. Links down below.

https://www.mcbbs.net/thread-917845-1-1.html
https://www.mcbbs.net/thread-709092-1-1.html

**Comment by LeePC** [comment]
한국인이신거같은데.....
soma 리소스팩은 바이두로만 다운로드가 가능하고
파티클모드는 mcbbs 계정이 있어야됩니다

그리고 그영상 주인입니다

**Comment by ghost** [comment]
와 엄청난 분이 저에게 도움을 ㄷㄷ
감사합니다!

**Comment by ghost** [comment]
와 엄청난 분이 저에게 도움을 ㄷㄷ
감사합니다!
그리고 알려주신 팁 덕분에 해결했네요 ㄷㄷㄷㄷ
물론 상업적인용도로는 사용하지 않을거고 같은 반 친구에게 자랑질(?)해먹으려구요 ㅋㅋ
