### ISSUE TITLE
?? what is this?

### ISSUE THREAD

**Issue by ghost** [haveyouwantto/ParticleMusicGenerator#5]
color = (trackNum % 2 == 0) ? "1 0.4 0.65" : "0.21 1 0.83";

what is this var(?)

**Comment by haveyouwantto** [comment]
the particle color

**Comment by ghost** [comment]
it's a [LaTeX]?

**Comment by ghost** [comment]
and can you update out folder in file? ||(or) 
Can I share this file? 
it's a your project jar(to exe) file.
if you choice sure > can you give me ----cradit?----

[PMM v1.2 (console version).zip](https://github.com/haveyouwantto/ParticleMusicGenerator/files/5012261/PMM.v1.2.console.version.zip)

**Comment by ghost** [comment]
* PMM : PaticleMusicMinecraft

**Comment by haveyouwantto** [comment]
This project is using MIT license, so of course you can share, just give me credit.

**Comment by ghost** [comment]
--------cradit----------
link : https://github.com/haveyouwantto/ParticleMusicGenerator/
make : haveyouwantto
------------------------

?

**Comment by ghost** [comment]
i hava a 

.exe file
+color input
+block and id input
+dir input
+midi file name input
+function name input
(test5 ver)

**Comment by haveyouwantto** [comment]
that's fine.

**Comment by LeePC** [comment]
일단 단도진입적으로 말할게요
이 개발자는 사실상 공부하면서 개발을 하시는데
님은 이렇게 개발하면서 자랑하시면 저분만 자존심 구겨지는거나 마찬가지인데
한국인이라는 이미지가 병신취급받는거나 마찬가지인데 구지 이렇게 하셔도 좋은건가요??

**Comment by ghost** [comment]
그거 알려드릴까요 저도 중학생이고요 개발 하루에 1시간 하기도 어려워요 그리고 친구들한테 나눠주려고하는데 기분나쁘실까봐 물어본거구요 저 기능은 원래 프로젝트 안에 있는 코드에 input(scanner)모듈만 추가해서 배포한다고 알려준건데요 님이야말로 왜 그러시는거죠? 제가 언제 자랑했나요?
내가 힘들게 만든거 조금 수정해서 온라인에 쭈리는 기분 아니까 이러는건데요
